### ISSUE TITLE
Expanding community

### ISSUE THREAD

**Issue by F3T1W** [AinTunez/DarkScript3#10]
I'm new at modding, what are you thinking about updating the app for elden ring in future, if so, at what time approximately?

**Comment by Hansiriver** [comment]
hello, sir. I cant open files with 3.3. Can you offer some help.
System.Exception: No resource named eldenring-common.emedf.json exists
   DarkScript3.Resource.Text(String s)
   DarkScript3.InstructionDocs.InitDocsFromResource(String streamPath)
   DarkScript3.InstructionDocs..ctor(String resource, EMEDF overrideDoc)
   DarkScript3.GUI.OpenEMEVDFile(String fileName, FileMetadata metadata, EMEVD evd, String jsText, Dictionary`2 extraFields)
   DarkScript3.GUI.OpenJSFile(String fileName)
   DarkScript3.GUI.OpenFile(String fileName, FileMetadata metadata)
   DarkScript3.GUI.OpenToolStripMenuItem_Click(Object sender, EventArgs e)
   System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   System.Windows.Forms.Control.WndProc(Message& m)
   System.Windows.Forms.ToolStrip.WndProc(Message& m)
   System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by F3T1W** [comment]
Tools For Updating ER Scripts Were Added, Thanks A Lot! 👺
